from pathlib import Path

DEFAULT_REFERENCE_ID = "default"
DEFAULT_REFERENCE_AUDIO_NAME = "sample.mp3"
DEFAULT_REFERENCE_TEXT_NAME = "sample.lab"

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_REFERENCE_AUDIO_PATH = REPOSITORY_ROOT / DEFAULT_REFERENCE_AUDIO_NAME
DEFAULT_REFERENCE_TEXT_PATH = REPOSITORY_ROOT / DEFAULT_REFERENCE_TEXT_NAME
